databases:
  - name: postgres
    ipAllowList: []
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: postgres
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false