default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: employee_reimbursement_dev
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: employee_reimbursement_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: employee_reimbursement_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432

